services:
  app:
    build:
      target: local
    command: concurrently -n tailwind,runserver "python manage.py tailwind start" "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./:/app
  proxy:
    environment:
      UPSTREAMS: app:8000
