services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dockerfiles/app.Dockerfile
      args:
        SECRET_KEY_FILE: /run/secrets/django-secret-key
        DEBUG: ${DEBUG}
    working_dir: /app
    environment:
      SECRET_KEY_FILE: /run/secrets/django-secret-key
      DEBUG: ${DEBUG}
      DB_PASSWORD_FILE: /run/secrets/db-password
      DB_HOST: ${DB_HOST}
    secrets:
      - django-secret-key
      - db-password
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
  proxy:
    depends_on:
      - app
    build:
      context: .
      dockerfile: dockerfiles/caddy.Dockerfile
    ports:
      - 80:8000
      - 443:8443
      - 443:8443/udp
    cap_add:
      - NET_ADMIN
    volumes:
      - proxy-data:/data
      - proxy-config:/config
    environment:
      UPSTREAMS: ${UPSTREAMS}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
  db:
    build:
      context: .
      dockerfile: dockerfiles/postgres.Dockerfile
    ports:
      - 5432:5432
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    secrets:
      - db-password
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
secrets:
  django-secret-key:
    environment: "DJANGO_SECRET_KEY"
  db-password:
    environment: "DB_PASSWORD"
volumes:
  db-volume:
  proxy-data:
  proxy-config:
