services:
  app:
    image: ghcr.io/getogrand/getogrand-hypermedia-app
    build:
      target: prod
      platforms:
        - "linux/x86_64"
    command: sh -c "uv run python manage.py migrate && uv run gunicorn"
    restart: unless-stopped
    ports:
      - 8000:8000
  proxy:
    image: ghcr.io/getogrand/getogrand-hypermedia-proxy
    build:
      platforms:
        - "linux/x86_64"
  db:
    image: ghcr.io/getogrand/getogrand-hypermedia-db
    build:
      platforms:
        - "linux/x86_64"
