services:
  app:
    image: ghcr.io/getogrand/getogrand-hypermedia-app
    build:
      target: prod
      platforms:
        - "linux/x86_64"
    command: sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 getogrand_hypermedia.asgi:application"
    restart: unless-stopped
    ports:
      - 80:8000
  proxy:
    image: ghcr.io/getogrand/getogrand-hypermedia-proxy
    build:
      platforms:
        - "linux/x86_64"
  db:
    image: ghcr.io/getogrand/getogrand-hypermedia-db
    build:
      platforms:
        - "linux/x86_64"
