services:
  app:
    image: 730335367003.dkr.ecr.ap-northeast-2.amazonaws.com/getogrand-hypermedia/app
    build:
      platforms:
        - "linux/x86_64"
    command: daphne -e ssl:8443:interface=0.0.0.0:privateKey=/app/localhost+2-key.pem:certKey=/app/localhost+2.pem getogrand_hypermedia.asgi:application
    restart: unless-stopped
    ports:
      - 8443:8443
  proxy:
    image: 730335367003.dkr.ecr.ap-northeast-2.amazonaws.com/getogrand-hypermedia/proxy
    build:
      platforms:
        - "linux/x86_64"
  db:
    image: 730335367003.dkr.ecr.ap-northeast-2.amazonaws.com/getogrand-hypermedia/db
    build:
      platforms:
        - "linux/x86_64"
