services:
  app:
    image: 730335367003.dkr.ecr.ap-northeast-2.amazonaws.com/getogrand-hypermedia/app
    build:
      platforms:
        - "linux/x86_64"
    command: sh -c "daphne -b 0.0.0.0 -p 8000 getogrand_hypermedia.asgi:application"
    restart: unless-stopped
  proxy:
    image: 730335367003.dkr.ecr.ap-northeast-2.amazonaws.com/getogrand-hypermedia/proxy
    build:
      platforms:
        - "linux/x86_64"
  db:
    image: 730335367003.dkr.ecr.ap-northeast-2.amazonaws.com/getogrand-hypermedia/db
    build:
      platforms:
        - "linux/x86_64"
