services:
  app:
    image: 730335367003.dkr.ecr.ap-northeast-2.amazonaws.com/getogrand-hypermedia/app
    build:
      target: prod
      platforms:
        - "linux/x86_64"
    command: sh -c "python manage.py migrate && gunicorn"
    restart: unless-stopped
    ports:
      - 8000:8000
  proxy:
    image: 730335367003.dkr.ecr.ap-northeast-2.amazonaws.com/getogrand-hypermedia/proxy
    build:
      platforms:
        - "linux/x86_64"
  db:
    image: 730335367003.dkr.ecr.ap-northeast-2.amazonaws.com/getogrand-hypermedia/db
    build:
      platforms:
        - "linux/x86_64"
