services:
  app-dev:
    depends_on:
      - db
    container_name: getogrand-hypermedia-app-dev
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      SECRET_KEY: /run/secrets/django-secret-key
      DEBUG: ${DEBUG}
      DB_PASSWORD: /run/secrets/db-password
      DB_HOST: ${DB_HOST}
    secrets:
      - django-secret-key
      - db-password
  db:
    container_name: getogrand-hypermedia-db
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=/run/secrets/db-password
    secrets:
      - db-password
secrets:
  django-secret-key:
    environment: "DJANGO_SECRET_KEY"
  db-password:
    environment: "DB_PASSWORD"
volumes:
  db-volume:
